const colors = require('tailwindcss/colors')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/*.{liquid,html,js}',
    './src/**/*.{liquid,html,js}',
    './public/*.{liquid,html,js}',
    './public/**/*.{liquid,html,js}',
  ],
  theme: {
    extend: {
      colors: {
        background: colors.white,
        'on-background': colors.black,
        primary: colors.emerald,
        'on-primary': {
          50: colors.black,
          100: colors.black,
          200: colors.black,
          300: colors.black,
          400: colors.black,
          500: colors.white,
          600: colors.white,
          700: colors.white,
          800: colors.white,
          900: colors.white,
          950: colors.white,
        },
        secondary: colors.sky,
        'on-secondary': {
          50: colors.black,
          100: colors.black,
          200: colors.black,
          300: colors.black,
          400: colors.black,
          500: colors.black,
          600: colors.white,
          700: colors.white,
          800: colors.white,
          900: colors.white,
          950: colors.white,
        },
        error: colors.red,
        'on-error': {
          50: colors.black,
          100: colors.black,
          200: colors.black,
          300: colors.black,
          400: colors.black,
          500: colors.black,
          600: colors.black,
          700: colors.white,
          800: colors.white,
          900: colors.white,
          950: colors.white,
        },
        warning: colors.amber,
        'on-warning': {
          50: colors.black,
          100: colors.black,
          200: colors.black,
          300: colors.black,
          400: colors.black,
          500: colors.black,
          600: colors.black,
          700: colors.white,
          800: colors.white,
          900: colors.white,
          950: colors.white,
        },
        success: colors.lime,
        'on-success': {
          50: colors.black,
          100: colors.black,
          200: colors.black,
          300: colors.black,
          400: colors.black,
          500: colors.black,
          600: colors.white,
          700: colors.white,
          800: colors.white,
          900: colors.white,
          950: colors.white,
        },
        disabled: colors.slate,
        'on-disabled': {
          50: colors.black,
          100: colors.black,
          200: colors.black,
          300: colors.black,
          400: colors.black,
          500: colors.black,
          600: colors.white,
          700: colors.white,
          800: colors.white,
          900: colors.white,
          950: colors.white,
        },
      },
    },
  },
  plugins: [],
}
